### ISSUE TITLE
Move repo into rust-amplify org

### ISSUE THREAD

**Issue by dr-orlovsky** [cyphernet-dao/rust-microservices#6]
Since this crate has nothing to do with encryption and privacy-preserving networking per se (which is the goal of this github org) and rather is a generic-purpose network service library I plan to move it into https://github.com/rust-amplify organization where it seems to be more appropriate (it already contains few other microservice- and networking-related crates).

I'll do that next week if I wouldn't receive objections from @zkao @cryptoquick and @Lederstrumpf 

NB: While this crate is still used in LNP/BP nodes, from v0.10 they will switch from it onto https://github.com/rust-amplify/io-reactor thus this move wouldn't affect projects like RGB, LNP etc (a note for @zoedberg @nicbus)

**Comment by cryptoquick** [comment]
That makes sense. Will this also be a part of the move away from ZMQ?

Also, be sure to take a look at Nakamoto's reactor model for inspiration: https://github.com/cloudhead/nakamoto/tree/master/net

**Comment by dr-orlovsky** [comment]
@cryptoquick the Nakamoto reactor was the starting point for creating  https://github.com/rust-amplify/io-reactor; in fact io-reactor IS nakamoto reactor with some slight enhancements (like more generic, able to work with worker threads etc).

As for ZMQ, yes, eventually all repos will move out of it

**Comment by cryptoquick** [comment]
Excellent! Maybe you can offer a PR to replace the Nakamoto reactor, then; that might help reduce maintainership burden, and generalize their implementation.

**Comment by dr-orlovsky** [comment]
We discussed with @cloudhead that eventually Nakamoto will use the new reactor - but still have a lot of other priorities to do before that

**Comment by dr-orlovsky** [comment]
After certain considerations I decided not to do that. First, it introduces circular dependencies, since this repo depends on other repo from this org (`internet2`), which in turn depends on repos from @rust-amplify org. Second, `microservices` were designed for running microservice architectures using mixnets, encryption etc, so it seems that this org is the right place for it.

With `netservices` v0.1 release I am moving all our nodes to it, but eventually here I will put some higher-level code to build nodes and servers with microservice architecture using stuff from `netservices` and `reactor`
